In [2]:
import pandas as pd
import os
import numpy as np

In [159]:
files = [arff for arff in os.listdir('.') if arff.endswith(".csv")]

i = 0
dataset = files[i]
print(dataset)

page-blocks.csv

In [160]:
df = pd.read_csv(dataset)
df
# df['c'].value_counts()
# df.pop('ID')
# # df['class:'].value_counts()

# df.rename(columns={"class:": 'class'}, inplace=True)
# df.loc[df["class"] == "g", "class"] = 0
# df.loc[df["class"] == "h", "class"] = 1
# df['class'].value_counts()


# df.rename(columns={"Class": 'class'}, inplace=True)
# df.loc[df["class"] == "malignant", "class"] = 1
# df.loc[df["class"] == "benign", "class"] = 0
# df['class'].value_counts()
# df

# y = df.pop("'class'")
# df['class'] = y

# df


# df['class'].value_counts()

# df.rename(columns={"'Class'": 'class'}, inplace=True)
# df.loc[df["class"] == 'negative', "class"] = 0
# df.loc[df["class"] == 'positive', "class"] = 1

# df['class'].value_counts()

# df.rename(columns={'Class': 'class'}, inplace=True)
# df.loc[df["class"] == 1, "class"] = 1
# df.loc[df["class"] == 2, "class"] = 0
# df['class'].value_counts()

df.rename(columns={'binaryClass': 'class'}, inplace=True)
df.loc[df["class"] == 'P', "class"] = 1
df.loc[df["class"] == 'N', "class"] = 0
df['class'].value_counts()

# df.loc[df["Sex"] == 'M', "Sex"] = 0
# df.loc[df["Sex"] == 'F', "Sex"] = 1

# df


# y = df.pop("'int0'")
# df['class'] = y

,height,lenght,area,eccen,p_black,p_and,mean_tr,blackpix,blackand,wb_trans,binaryClass
0,5,7,35,1.400,0.400,0.657,2.33,14,23,6,P
1,6,7,42,1.167,0.429,0.881,3.60,18,37,5,P
2,6,18,108,3.000,0.287,0.741,4.43,31,80,7,P
3,5,7,35,1.400,0.371,0.743,4.33,13,26,3,P
4,6,3,18,0.500,0.500,0.944,2.25,9,17,4,P
...,...,...,...,...,...,...,...,...,...,...,...
5468,4,524,2096,131.000,0.542,0.603,40.57,1136,1264,28,N
5469,7,4,28,0.571,0.714,0.929,10.00,20,26,2,P
5470,6,95,570,15.833,0.300,0.911,1.64,171,519,104,P
5471,7,41,287,5.857,0.213,0.801,1.36,61,230,45,P
5472,8,1,8,0.125,1.000,1.000,8.00,8,8,1,N

In [156]:
df

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V12,V13,V14,V15,V16,V17,V18,V19,V20,class
0,849,2177,598,1689,3114,-3406,3799,-2642,1578,-181,...,1633,4664,1081,-1172,-166,578,1664,309,-3028,1
1,947,543,782,-449,-8,1316,756,-61,1604,1686,...,-382,1259,608,-2292,1008,2687,-1422,-606,2374,0
2,759,-314,898,-1743,2003,1117,911,136,-489,-144,...,112,598,474,2026,1431,-336,79,1123,302,0
3,531,1374,517,1226,1122,-4,-1227,2277,1083,888,...,1063,2454,587,-744,1216,916,-476,6,-477,0
4,-1443,1065,2071,207,-865,-786,2655,-366,971,-341,...,4195,-117,-2694,14,4097,1356,-944,-602,2348,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7395,607,1539,139,1378,-2178,-1,404,2064,653,-631,...,783,1106,1264,57,-413,136,-509,1423,1142,0
7396,-122,-1654,-395,278,-193,-463,1364,37,1998,2278,...,-1856,136,4604,-1117,-5735,173,1505,-1098,-5196,1
7397,-1854,1225,-2469,-351,1193,-3922,-2314,3565,2946,1463,...,2214,-1199,-1152,-1815,1051,-2244,2871,-3462,1619,1
7398,2604,-1541,1298,-742,-238,-1004,127,1056,-27,33,...,45,241,-635,1274,157,602,606,573,-751,0
7399,-239,472,2795,-1672,-802,594,-1449,336,-922,-1783,...,1477,3247,777,1298,-277,-3445,-2969,-132,3362,1

In [157]:
size = len(df)
p_proportion = np.sum(df['class'].to_numpy()) / len(df)
n_proportion = 1.0 - p_proportion

print(p_proportion * size * 0.3)
print(n_proportion * size * 0.3)

1099.2
1120.7999999999997

In [158]:
df.to_csv('./treated_datasets/' + dataset, index=False)

In [ ]:
# datasets_path = "./merged/datasets/"
# description_table = pd.DataFrame(columns=['dataset', 'size', 'positives_distribution', 'negatives_distribution'])

# for dataset in datasets:
#     df = pd.read_csv(datasets_path + dataset)

#     name = dataset.split('.csv')[0]
#     size = len(df)
#     p_proportion = np.sum(df['class'].to_numpy()) / len(df)
#     n_proportion = 1.0 - p_proportion

#     description_table.loc[len(description_table)] = [name, size, round(p_proportion, 2), round(n_proportion, 2)]

# description_table.to_csv('./merged/plot_data/dataset_description_table.csv', index=False)